In [1]:
import subprocess
import sys

# Required libraries for your code
libraries = [
    "numpy",
    "scikit-learn",
    "tensorflow"
]

print("Installing required libraries...\n")

for lib in libraries:
    try:
        subprocess.check_call([sys.executable, "-m", "pip", "install", lib])
        print(f"{lib} installed successfully!")
    except Exception as e:
        print(f"Failed to install {lib}: {e}")

print("\nAll required libraries installed successfully!")

import numpy as np
from sklearn.ensemble import VotingClassifier
from sklearn.base import BaseEstimator, ClassifierMixin
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import GlobalAveragePooling2D, Dense, Dropout, BatchNormalization
from tensorflow.keras.applications import InceptionResNetV2
from tensorflow.keras.preprocessing.image import ImageDataGenerator

Installing required libraries...

numpy installed successfully!
scikit-learn installed successfully!
tensorflow installed successfully!

All required libraries installed successfully!


In [2]:
# Define image dimensions and batch size
img_height, img_width = 128, 128
batch_size = 32
# Define directories for training and testing data
train_data_dir = "../dataset/train"
test_data_dir = "../dataset/test"

In [3]:
# Data augmentation for training images
train_datagen = ImageDataGenerator(
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    rescale=1./255  # Normalize pixel values
)

# Data augmentation for testing images (only rescale)
test_datagen = ImageDataGenerator(rescale=1./255)


In [4]:
# Create data generators for training and testing
train_generator = train_datagen.flow_from_directory(
    train_data_dir,
    target_size=(img_height, img_width),
    batch_size=batch_size,
    class_mode='categorical'
)

test_generator = test_datagen.flow_from_directory(
    test_data_dir,
    target_size=(img_height, img_width),
    batch_size=batch_size,
    class_mode='categorical',
    shuffle=False  # No need to shuffle for evaluation
)



Found 1174 images belonging to 14 classes.
Found 428 images belonging to 14 classes.


In [5]:
# Define the VGG16 base model
def create_InceptionResNetV2_model():
    InceptionResNetV2_model = InceptionResNetV2(
        include_top=False, 
        input_shape=(img_height, img_width, 3)
        )
    InceptionResNetV2_model.trainable = False

    model = Sequential([
        InceptionResNetV2_model,
        GlobalAveragePooling2D(),
        Dense(64, activation='relu'),
        BatchNormalization(),
        Dropout(0.2),
        Dense(14, activation='sigmoid')
    ])
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    print(model.summary())
    return model




In [6]:
#MODEL fit
model = create_InceptionResNetV2_model()
model.fit(train_generator, epochs=15, validation_data=test_generator)



219055592/219055592 ━━━━━━━━━━━━━━━━━━━━ 74s 0us/step


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ inception_resnet_v2             │ (None, 2, 2, 1536)     │    54,336,736 │
│ (Functional)                    │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling2d        │ (None, 1536)           │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 64)             │        98,368 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_203         │ (None, 64)             │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 14)             │           910 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 54,436,270 (207.66 MB)

 Trainable params: 99,406 (388.30 KB)

 Non-trainable params: 54,336,864 (207.28 MB)

None
Epoch 1/15
37/37 ━━━━━━━━━━━━━━━━━━━━ 33s 555ms/step - accuracy: 0.3322 - loss: 2.1005 - val_accuracy: 0.4836 - val_loss: 1.7815
Epoch 2/15
37/37 ━━━━━━━━━━━━━━━━━━━━ 15s 414ms/step - accuracy: 0.5341 - loss: 1.3996 - val_accuracy: 0.6121 - val_loss: 1.2238
Epoch 3/15
37/37 ━━━━━━━━━━━━━━━━━━━━ 15s 409ms/step - accuracy: 0.6193 - loss: 1.1933 - val_accuracy: 0.6472 - val_loss: 1.0770
Epoch 4/15
37/37 ━━━━━━━━━━━━━━━━━━━━ 15s 408ms/step - accuracy: 0.6746 - loss: 1.0383 - val_accuracy: 0.7033 - val_loss: 0.9741
Epoch 5/15
37/37 ━━━━━━━━━━━━━━━━━━━━ 15s 411ms/step - accuracy: 0.7002 - loss: 0.9248 - val_accuracy: 0.6121 - val_loss: 1.0919
Epoch 6/15
37/37 ━━━━━━━━━━━━━━━━━━━━ 15s 412ms/step - accuracy: 0.7027 - loss: 0.8872 - val_accuracy: 0.5818 - val_loss: 1.1360
Epoch 7/15
37/37 ━━━━━━━━━━━━━━━━━━━━ 15s 407ms/step - accuracy: 0.7368 - loss: 0.8259 - val_accuracy: 0.6098 - val_loss: 1.0615
Epoch 8/15
37/37 ━━━━━━━━━━━━━━━━━━━━ 16s 417ms/step - accuracy: 0.7726 - loss: 0.7486 - val

In [7]:
#predict
predictions = model.predict(test_generator)



14/14 ━━━━━━━━━━━━━━━━━━━━ 11s 565ms/step


In [8]:
print(predictions)
#calculate accuracy
from sklearn.metrics import accuracy_score
y_pred = np.argmax(predictions, axis=1)
y_true = test_generator.classes
accuracy = accuracy_score(y_true, y_pred)
print(accuracy)

[[0.9064804  0.7891522  0.9032075  ... 0.324916   0.20997846 0.23667106]
 [0.87522167 0.74692535 0.8733815  ... 0.2960344  0.1284273  0.12108637]
 [0.8586676  0.8549925  0.67433745 ... 0.7257797  0.27660054 0.22421841]
 ...
 [0.01512887 0.24586885 0.15145156 ... 0.81875604 0.6512653  0.99964964]
 [0.01773725 0.45926374 0.11630887 ... 0.5871315  0.3145447  0.99894464]
 [0.03183354 0.23131205 0.0692177  ... 0.45868346 0.2737241  0.9957326 ]]
0.7570093457943925


In [9]:
# Save the trained model
model.save("../model_saved_files/InceptionResNetV2.h5")
print("Model saved successfully!")

Model saved successfully!
